const data = {
    products: [
        {
            name: 'plant1',
            slug: 'plant1',
            category: 'indoor/outdoor',
            image: '/images/Monstera1.jpeg',
            price: 100,
            countInStock: 20,
            description: 'info1',

        },
        {
            name: 'plant2',
            slug: 'plant2',
            category: 'indoor/outdoor',
            image: 'images/Monstera1.jpeg',
            price: 100,
            countInStock: 20,
            description: 'info1',
        },
        {
            name: 'plant3',
            slug: 'plant3',
            category: 'indoor/outdoor',
            image: 'images/Monstera1.jpeg',
            price: 100,
            countInStock: 20,
            description: 'info1',
        },
        {
            name: 'plant4',
            slug: 'plant4',
            category: 'indoor/outdoor',
            image: 'images/Monstera1.jpeg',
            price: 100,
            countInStock: 20,
            description: 'info1',
        },
        // {
        //     name: 'plant5',
        //     slug: 'slug5',
        //     category: 'indoor/outdoor',
        //     image: 'images/Monstera1.jpeg',
        //     price: 100,
        //     countInStock: 20,
        //     description: 'info1',
        // },
        // {
        //     name: 'plant1',
        //     slug: 'slug1',
        //     category: 'indoor/outdoor',
        //     image: 'images/Monstera1.jpeg',
        //     price: 100,
        //     countInStock: 20,
        //     description: 'info1',
        // },
        // {
        //     name: 'plant1',
        //     slug: 'slug1',
        //     category: 'indoor/outdoor',
        //     image: 'images/Monstera1.jpeg',
        //     price: 100,
        //     countInStock: 20,
        //     description: 'info1',
        // },
        // {
        //     name: 'plant1',
        //     slug: 'slug1',
        //     category: 'indoor/outdoor',
        //     image: 'images/Monstera1.jpeg',
        //     price: 100,
        //     countInStock: 20,
        //     description: 'info1',
        // },
        // {
        //     name: 'plant1',
        //     slug: 'slug1',
        //     category: 'indoor/outdoor',
        //     image: 'images/Monstera1.jpeg',
        //     price: 100,
        //     countInStock: 20,
        //     description: 'info1',
        // },
        // {
        //     name: 'plant1',
        //     slug: 'slug1',
        //     category: 'indoor/outdoor',
        //     image: 'images/Monstera1.jpeg',
        //     price: 100,
        //     countInStock: 20,
        //     description: 'info1',
        // }
    ]
}

export default data;